config/routes.rb
W2lProto::Application.routes.draw do
  
  get 'auth/:provider/callback' => 'sessions#create'
  get 'auth/failure' => redirect('/')
  get "signout" => "sessions#destroy", as: "signout"
  
  get "/users/:id" => "users#show", as: "user"
  post "checkin" => "users#check_in", as: "check_ins"
  get "currentuser/checkins" => "users#current_user_check_ins"
  
  get "tags/index", as: "tags"
  get "tags.json" => "tags#tags_json"
  post "liketag" => "tags#like", as: "likes"
  post "disliketag" => "tags#dislike", as: "dislikes"
  delete "like/:id" => "tags#unlike", as: "like"
  delete "dislike/:id" => "tags#undislike", as: "dislike"
  
  get "localities/index", as: "localities"
  get "locality/:name" => "localities#show", as: "locality"
  get "locality/:id/edit" => "localities#edit"
  patch "locality/:id" => "localities#hantagace"
  

  root 'users#index'

  

end

app/models/check_in.rb
class CheckIn < ActiveRecord::Base
  belongs_to :locality
  belongs_to :user
end

app/models/dislike.rb
class Dislike < ActiveRecord::Base
  belongs_to :tag
  belongs_to :user
end

app/models/hantagace.rb
class Hantagace < ActiveRecord::Base
  belongs_to :locality
  belongs_to :tag
end

app/models/like.rb
class Like < ActiveRecord::Base
  belongs_to :tag
  belongs_to :user
end

app/models/locality.rb
class Locality < ActiveRecord::Base
  has_many :check_ins
  has_many :users, through: :check_ins
  has_many :hantagaces
  has_many :tags, through: :hantagaces
  attr_reader :tag_tokens
  
  def tag_tokens=(ids)
    self.tag_ids = ids.split(",")
  end
end

app/models/tag.rb
class Tag < ActiveRecord::Base
  has_many :likes
  has_many :user, through: :likes
  has_many :dislikes
  has_many :user, through: :dislikes
  has_many :hantagaces
  has_many :localities, through: :hantagaces
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :likes
  has_many :tags, through: :likes
  has_many :dislikes
  has_many :tags, through: :dislikes
  has_many :check_ins
  has_many :localities, through: :check_ins
  
  def self.from_omniauth(auth)
    where(auth.slice(:provider, :uid)).first_or_initialize.tap do |user|
      user.provider = auth.provider
      user.uid = auth.uid
      user.name = auth.info.name
      user.oauth_token = auth.credentials.token
      user.oauth_expires_at = Time.at(auth.credentials.expires_at)
      user.image = auth.info.image
      user.urls = auth.info.urls.Facebook
      user.email = auth.info.email
      user.save!
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  
  private
  
  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
  
  helper_method :current_user
end

app/controllers/localities_controller.rb
class LocalitiesController < ApplicationController
  def index
    @localities = Locality.all
    @total_localities = Locality.all.count
    @total_users = User.all.count
    @total_hanged_tags = Hantagace.all.count
  end

  def show
    @locality = Locality.find_by(name: params[:name])
  end
  
  def edit
    @locality = Locality.find(params[:id])
  end
  
  def hantagace
    locality = Locality.find(params[:id])
    locality.update_attributes!(hantagace_params)
    redirect_to root_url #should stay in same page
  end
  
  private
  
  def hantagace_params
    params.require(:locality).permit(:locality_id, :tag_tokens)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    user = User.from_omniauth(env["omniauth.auth"])
    session[:user_id] = user.id
    redirect_to root_url
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_url
  end
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  def index
    @tags = Tag.all.sort_by { |tag| -(tag.likes.count*3 - tag.dislikes.count*2) }.take(100)
    @total_tags = Tag.all.count
    @total_likes = Like.all.count
    @total_dislikes = Dislike.all.count
    @like = Like.new
    @dislike = Dislike.new
  end
  
  def tags_json
    tags = Tag.order(:name)
    render json: tags.where("name like ?", "%#{params[:q]}%")
  end
  
  def like
    @like = Like.new(like_params)
    begin
      if @like.save
        redirect_to :back
      else
        render '/public/500', layout: false
      end
    rescue ActiveRecord::RecordNotUnique
      render '/public/500', layout: false
    end
  end
  
  def unlike
    @like = Like.destroy(params[:id])
    redirect_to :back
  end
  
  def dislike
    @dislike = Dislike.new(dislike_params)
    begin
      if @dislike.save
        redirect_to :back
      else
        render '/public/500', layout: false
      end
    rescue ActiveRecord::RecordNotUnique
      render '/public/500', layout: false
    end
  end
  
  def undislike
    @dislike = Dislike.destroy(params[:id])
    redirect_to :back
  end
  
  private
  
  def like_params
    params.require(:like).permit(:tag_id, :user_id)
  end
  def dislike_params
    params.require(:dislike).permit(:tag_id, :user_id)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @check_in = CheckIn.new
  end
  
  def show
    if current_user
      @user = User.find_by_id(params[:id])
    else
      redirect_to root_url
    end
  end

  def check_in
    begin
      @locality = Locality.find_or_create_by(name: check_in_params[:locality_name])
      @check_in = CheckIn.create(locality_id: @locality.id, user_id: check_in_params[:user_id])
      redirect_to root_url
    rescue ActiveRecord::RecordNotUnique
      render '/public/500', layout: false
    end
  end
  
  def current_user_check_ins
    # get name (locality) of all current user check ins
    @current_user_check_ins = Locality.joins(:check_ins).where(check_ins: { user_id: current_user.id }).pluck(:name)
    respond_to do |format|
      format.json { render :json => @current_user_check_ins }
    end
  end
  
  private
  
  def check_in_params
    params.require(:check_in).permit(:locality_id, :user_id, :locality_name)
  end
  
  def locality_params
    params.require(:locality).permit(:name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  #return path to full screen background image, installed in application layout
  def random_bg
    blacklist = [".", "..",".DS_Store"]
    file_names = Dir.entries("#{Rails.root}/app/assets/images/bg-fullscreen/")
    blacklist.each do |blacklsited|
      file_names.delete(blacklsited)
    end
    "bg-fullscreen/#{file_names.shuffle.first}"
  end
  #sorted samples of items for chars of tags & localities
  def chart_sorted_sample(number, array_of_hashes)
    array_of_hashes.sample(number).sort_by {|item| item[:name]}
  end
end

app/helpers/localities_helper.rb
module LocalitiesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_form.html.erb
<%= form_for @locality, remote: true do |f| %>
  <div class="grid">
    <div class="grid__item one-half">
    <%= f.submit "Hantagace", class: "submit-titleize-button" %> <%= link_to "BACK", "#", class: "md-close font-large uppercase margin-left-normal" %>
    </div>
    <div class="grid__item one-half">
    <%= f.text_field :tag_tokens, data: {load: @locality.tags}, id: "locality_tag_tokens_#{@locality.name}" %>
    </div>
  </div>
<% end %>

app/views/layouts/_new_hantagace_form.html.erb
<div class="md-modal md-effect" id="modal">
  <div class="md-content">
    <h1 class="margin-normal">Hang a tag</h1>
    <div class="grid" id="hantagace-form">
      <% if current_user && current_user.localities.any? %>
        <ul class="grid__item one-whole menu">
          <% current_user.localities.each do |locality| %>
            <li class="font-large uppercase menu-item">
              <%= link_to locality.name, controller: "localities", action: "edit", id: locality.id, remote: true %>
            </li>
          <% end %>
        </ul>
        <div class="grid__item one-whole" id="hantagace_form">
          choose locality
        </div>
      <% else %>
        <div class="grid__item one-whole margin-normal">
          You haven't check-in, do one.
        </div>
      <% end %>
    </div>
  </div>
</div>
<div class="md-overlay"></div>

<script type="text/javascript">
  /*!
   * classie - class helper functions
   * from bonzo https://github.com/ded/bonzo
   * 
   * classie.has( elem, 'my-class' ) -> true/false
   * classie.add( elem, 'my-new-class' )
   * classie.remove( elem, 'my-unwanted-class' )
   * classie.toggle( elem, 'my-class' )
   */

  /*jshint browser: true, strict: true, undef: true */
  /*global define: false */

  ( function( window ) {

  'use strict';

  // class helper functions from bonzo https://github.com/ded/bonzo

  function classReg( className ) {
    return new RegExp("(^|\\s+)" + className + "(\\s+|$)");
  }

  // classList support for class management
  // altho to be fair, the api sucks because it won't accept multiple classes at once
  var hasClass, addClass, removeClass;

  if ( 'classList' in document.documentElement ) {
    hasClass = function( elem, c ) {
      return elem.classList.contains( c );
    };
    addClass = function( elem, c ) {
      elem.classList.add( c );
    };
    removeClass = function( elem, c ) {
      elem.classList.remove( c );
    };
  }
  else {
    hasClass = function( elem, c ) {
      return classReg( c ).test( elem.className );
    };
    addClass = function( elem, c ) {
      if ( !hasClass( elem, c ) ) {
        elem.className = elem.className + ' ' + c;
      }
    };
    removeClass = function( elem, c ) {
      elem.className = elem.className.replace( classReg( c ), ' ' );
    };
  }

  function toggleClass( elem, c ) {
    var fn = hasClass( elem, c ) ? removeClass : addClass;
    fn( elem, c );
  }

  var classie = {
    // full names
    hasClass: hasClass,
    addClass: addClass,
    removeClass: removeClass,
    toggleClass: toggleClass,
    // short names
    has: hasClass,
    add: addClass,
    remove: removeClass,
    toggle: toggleClass
  };

  // transport
  if ( typeof define === 'function' && define.amd ) {
    // AMD
    define( classie );
  } else {
    // browser global
    window.classie = classie;
  }

  })( window );
</script>

<script type="text/javascript">
  var ModalEffects = (function() {

    function init() {

      var overlay = document.querySelector( '.md-overlay' );

      [].slice.call( document.querySelectorAll( '.md-trigger' ) ).forEach( function( el, i ) {

        var modal = document.querySelector( '#' + el.getAttribute( 'data-modal' ) ),
          close = modal.querySelector( '.md-close' );

        function removeModal( hasPerspective ) {
          classie.remove( modal, 'md-show' );
        }

        function removeModalHandler() {
          removeModal( classie.has( el, 'md-setperspective' ) ); 
        }

        el.addEventListener( 'click', function( ev ) {
          classie.add( modal, 'md-show' );
          overlay.removeEventListener( 'click', removeModalHandler );
          overlay.addEventListener( 'click', removeModalHandler );
        });

        close.addEventListener( 'click', function( ev ) {
          ev.stopPropagation();
          removeModalHandler();
        });

      } );

    }

    init();

  })();
</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>W2lProto</title>
  <link href='http://fonts.googleapis.com/css?family=Abel|Squada+One|Medula+One' rel='stylesheet' type='text/css'>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= stylesheet_link_tag params[:controller] %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <script src="http://maps.google.com/maps/api/js?sensor=false&language=en"></script>
  <%= csrf_meta_tags %>
</head>
<body>
  <div id="bg-fullscreen">
    <%= image_tag random_bg %>
  </div>
  <nav class="grid">
    <div class="grid__item text-align-center one-whole">
      <ul class="menu">
        <li class="menu-item"><%= link_to "home", root_path %></li>
        <li class="menu-item"><%= link_to "localities", localities_path %></li>
        <li class="menu-item"><%= link_to "tags", tags_path %></li>
      </ul>
      <% if current_user %>
        <ul class="menu">
          <li class="menu-item"><%= link_to "profile", user_path(current_user.id) %></li>
          <li class="menu-item"><%= link_to "sing out", signout_path %></li>
        </ul>
      <% else %>
      <ul class="menu">
        <li class="menu-item"><%= link_to "Sign in", "/auth/facebook", id: "sign_in" %></li>
      </ul>
      <% end %>
    </div>
  </nav>
  <div class="grid margin-normal">
    <header class="grid__item one-whole">
      <%= image_tag 'logohantagace.png', alt: 'hantagace' %>
      <% if current_user %>
        <button class="md-trigger" data-modal="modal" id="add-hantagace">+</button>
        <%= image_tag current_user.image, alt: 'user-image', id: 'user-image' %>
      <% end %>
    </header>
  </div>
  <section class="grid">
    <%= yield %>
  </section>
  <%= render 'layouts/new_hantagace_form'%>
</body>
</html>

app/views/localities/_item.html.erb
<li class="grid <%= chart_class_item %>">
  <div class="grid__item one-twelfth">
    <%= index + 1 %>.
  </div>
  <h1 class="grid__item chart-item-name five-twelfths">
    <%= link_to locality.name, locality_path(locality.name) %>
  </h1>
  <div class="grid__item one-twelfth">
    <%= locality.check_ins.count %> CI
  </div>
  <div class="grid__item chart-item-last-column five-twelfths">
    <% if locality.tags.any? %>
      <% chart_sorted_sample(4, locality.tags).each do |tag| %>
        <span class="margin-right-normal"><%= tag.name %></span>
      <% end %>
    <% else %>
      <span class="margin-right-normal">no one tag was hanged</span>
    <% end %>
  </div>
</li>

app/views/localities/edit.js.erb
$('#hantagace_form').html('<%= j render "layouts/form" %>');

$('#locality_tag_tokens_<%= @locality.name %>').tokenInput('/tags.json', {
  prePopulate: $('#locality_tag_tokens_<%= @locality.name %>').data('load')
});

app/views/localities/index.html.erb
<div class="grid--center margin-double">
  <div class="grid__item three-quarters">
    <div class="margin-normal">
      <div class="grid">
        <div class="grid__item one-third grid--center">
          <div class="stat-label">total number of localities</div>
          <div class="stat-number"><%= @total_localities %></div>
        </div>        
        <div class="grid__item one-third grid--center">
          <div class="stat-label">total users</div>
          <div class="stat-number"><%= @total_users %></div>
        </div>        
        <div class="grid__item one-third grid--center">
          <div class="stat-label">total hanged tags</div>
          <div class="stat-number"><%= @total_hanged_tags %></div>
        </div>
      </div>
    </div>
    <ul>
    <% @localities.each_with_index do |locality, index| %>
      <% if index < 10 %>
        <%= render "item", { chart_class_item: "chart-top-item", index: index, locality: locality } %>
      <% else %>
        <%= render "item", { chart_class_item: "chart-item", index: index, locality: locality } %>
      <% end %>
    <% end %>
    </ul>
  </div>
</div>

app/views/localities/show.html.erb
<div class="grid__item one-whole margin-normal">
  <div id="locality-name-locality-show">
    <h1><%= @locality.name %></h1>
  </div>
</div>
<div class="grid__item one-half">
  <div id="locality-chart-position-locality-show">
    <span>0th</span> in chart
  </div>
</div>
<div class="grid__item one-half">
  <div id="locality-tag-list-locality-show">
    <span>tag</span> list
  </div>
</div>

app/views/tags/_item.html.erb
<li class="grid <%= chart_class_item %>">
  <div class="grid__item one-twelfth">
    <%= index + 1 %>.
  </div>
  <h1 class="grid__item chart-item-name four-twelfths">
    <%= tag.name %>
  </h1>
  <div class="grid__item one-twelfth">
    <% if current_user %>
      <% if tag.likes.find_by(user_id: current_user.id) %>
        <%= link_to "NLL", tag.likes.find_by(user_id: current_user.id), method: :delete %>
      <% elsif tag.dislikes.find_by(user_id: current_user.id) %>
        <%= link_to "NLD", tag.dislikes.find_by(user_id: current_user.id), method: :delete %>
      <% else %>
        <%= form_for @like do |f| %>
          <%= f.hidden_field :tag_id, value: tag.id %>
          <%= f.hidden_field :user_id, value: current_user.id %>
          <%= f.submit "L", class: "submit-like-dislike-icon" %>
        <% end %> /
        <%= form_for @dislike do |f| %>
          <%= f.hidden_field :tag_id, value: tag.id %>
          <%= f.hidden_field :user_id, value: current_user.id %>
          <%= f.submit "D", class: "submit-like-dislike-icon" %>
        <% end %>
      <% end %>
    <% end %>
  </div>
  <div class="grid__item chart-item-love-hate one-twelfth">    
    <%= tag.likes.count %> / <%= tag.dislikes.count %>
  </div>
  <div class="grid__item chart-item-last-column five-twelfths">
    <% if tag.localities.any? %>
      <% chart_sorted_sample(3, tag.localities).each do |locality| %>
        <span class="margin-right-normal"><%= link_to locality.name, locality_path(locality.name) %></span>
      <% end %>
    <% else %>
      <span class="margin-right-normal">there is no one place with this tag</span>
    <% end %>
  </div>
</li>

app/views/tags/index.html.erb
<div class="grid--center margin-double">
  <div class="grid__item three-quarters">
    <div class="margin-normal">
      <div class="grid">
        <div class="grid__item one-third grid--center">
          <div class="stat-label">total number of tags</div>
          <div class="stat-number"><%= @total_tags %></div>
        </div>        
        <div class="grid__item one-third grid--center">
          <div class="stat-label">total likes</div>
          <div class="stat-number"><%= @total_likes %></div>
        </div>        
        <div class="grid__item one-third grid--center">
          <div class="stat-label">total dislikes</div>
          <div class="stat-number"><%= @total_dislikes %></div>
        </div>
      </div>
    </div>
    <ul>
    <% @tags.each_with_index do |tag, index| %>
      <% if index < 10 %>
        <%= render "item", { chart_class_item: "chart-top-item", index: index, tag: tag } %>
      <% else %>
        <%= render "item", { chart_class_item: "chart-item", index: index, tag: tag } %>
      <% end %>
    <% end %>
    </ul>
  </div>
</div>

app/views/users/index.html.erb
<div class="grid__item grid--center vertical-center one-whole">
  <div class="grid">
    <div class="grid__item one-whole">
      <% if current_user %>
            <span id="locality-name" class="font-large"></span>
            <%= form_for @check_in, name: "formcheckin" do |f| %>
              <%= f.hidden_field :locality_name, id: "form-field-locality-name", value: "" %>
              <%= f.hidden_field :user_id, value: current_user.id %>
              <%= f.submit "check in", class: "submit-titleize-button margin-left-normal" %>
            <% end %>
            <%= link_to "Explore it", "path of locality's link set by JS below", id: "explore_it", class: "submit-titleize-button margin-left-normal" %>
      <% else %>
        <div>
          <div id="user-subblock">
            <%= link_to "Sign in with Facebook", "/auth/facebook", id: "sign_in" %>
          </div>
          <%= image_tag "logofacebook.png", alt: 'Facebook logo', id: "logo-facebook" %>
        </div>
      <% end %>
    </div>
  </div>
</div>

<% if current_user %>
<script type="text/javascript">
  document.getElementById('explore_it').style.display = "none";
  if (navigator.geolocation) {
      navigator.geolocation.getCurrentPosition(function (position) {
          //get latitude & longitude
          var latitude = position.coords.latitude;
          var longitude = position.coords.longitude;
          var coord = new google.maps.LatLng(latitude,longitude);
          
          geocoder = new google.maps.Geocoder();
          
          geocoder.geocode({'latLng': coord}, function(results, status) {
            // check status of query
            switch (status) {
            case "OK":
              // iteration of the json response to the request
              for (var i = 0; i < results[0].address_components.length; i++) {
                  for (var j = 0; j < results[0].address_components[i].types.length; j++) {
                      if(results[0].address_components[i].types[j] == 'locality') {
                          var city_name = results[0].address_components[i].long_name;
                          
                          //set geoceded locality value to html tag
                          document.getElementById('locality-name').innerHTML= "Now you're in " + city_name;
                          
                          //set geocoded locality value to check in form
                          document.getElementById('form-field-locality-name').value = city_name;
                      }
                  }
              }
              break;
            case "ZERO_RESULTS":
              // if no one locality in the response on the query
              document.getElementById('locality-name').innerHTML= "Undefined locality";
              document.getElementById('new_check_in').remove();
              break;
            }
            
            //get current_user check ins from app db
            $.get("/currentuser/checkins").done(function(data) {
              
              //change button if user allready make check in in his locality
              for (i = 0; i < data.length; i++) {
                if (data[i] == city_name) {
                 document.getElementById('locality-name').innerHTML= "Check-in " + city_name;
                 document.getElementById('new_check_in').remove();
                 document.getElementById('explore_it').style.display = "inline-block";
                 
                 //set geocoded locality value to link_to "explore it"
                 document.getElementById('explore_it').href = "locality/" + city_name;
                }
              }
              
            });
            
          //end of geocoding
          });
      });
  } else {
    // if gecode fails  
    document.getElementById('locality-name').innerHTML= "Geolocation API is not supported in your browser.";
  }
</script>
<% end %>

app/views/users/show.html.erb
<div class="grid__item one-whole margin-normal">
  <div id="user-image-users-show">
    <%= image_tag "http://graph.facebook.com/#{@user.uid}/picture?width=100&height=100", alt: "user image" %>
  </div>
  <div id="user-data-users-show">
    <div id="user-name-users-show">
      <h1><%= @user.name %></h1>
    </div>
    <div id="user-beloved-tags-users-show">
      e.g. warm climate
    </div>
    <div id="user-hated-tags-users-show">
      e.g. low standard of living
    </div>
  </div>
</div>
<div class="grid--center">
  <div class="grid__item three-quarters">
    <p>Check-ins</p>
    <% if @user.check_ins.any? %>
    <ul class="grid">
      <% @user.check_ins.each do |check_in| %>
      <li class="user-checkin-item margin-normal">
        <div class="grid__item three-twelfths user-checkin-item-locality-name-users-show">
          <span class="font-large uppercase"><%= check_in.locality.name %></span>
          <div>check-in <%= l check_in.created_at %></div>
        </div>
        <div class="grid__item seven-twelfths user-checkin-item-locality-tags-users-show">
          <div>you did not have a single tag hanged for this locality</div>
          <div><span class="submit-button">add tag</span></div>
        </div>
        <div class="grid__item two-twelfths user-checkin-item-locality-info-users-show">
          check-in <%= l check_in.created_at %>
        </div>
      </li>
      <% end %>
    </ul>
    <% else %>
    <div>
      No one check-in yet
    </div>
    <% end %>
  </div>
</div>